language: node_js
sudo: required
node_js:
  - 9
before_install:
  - npm install -g unitejs-cli
  - npm install -g gulp
  - npm install -g cordova
  - unite configure --profile=ReactTypeScript --title="Cordova QuickStart" --packageName=unitejs-cordova-quickstart --outputDirectory=./
  - unite platform --operation=add --platformName=Cordova
  - cd www
install:
  - npm install
script: 
  - gulp build || travis_terminate 1
  - gulp unit || travis_terminate 1
  - gulp e2e-install --drivers=chrome@2.33 || travis_terminate 1
  - gulp e2e || travis_terminate 1
  - gulp build --buildConfiguration=prod || travis_terminate 1
  - gulp e2e || travis_terminate 1
  - gulp platform-cordova-dev --buildConfiguration=prod || travis_terminate 1
  - gulp platform-cordova-theme --buildConfiguration=prod || travis_terminate 1

  
